ALTER TABLE "User"
  ADD COLUMN "plusTrialStartedAt" TIMESTAMP(3),
  ADD COLUMN "plusTrialEndsAt" TIMESTAMP(3);

ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_OFFER_VIEWED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_STARTED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_SKIPPED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_ENDING_PROMPT_VIEWED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_UPGRADE_CLICKED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRIAL_EXPIRED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'PURCHASE_STARTED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'PURCHASE_COMPLETED';
