import SwiftUI

@MainActor final class AccountConnectionModel: ObservableObject {
    @Published var email = ""; @Published var code = ""; @Published var sent = false; @Published var loading = false; @Published var error: String?
    func request(_ env: AppEnvironment) async { loading = true; error = nil; do { let _: EmailOTPResponse = try await env.session.perform("/api/v1/auth/email/request", method: .post, body: EmailOTPRequest(email: email.trimmingCharacters(in: .whitespacesAndNewlines))); sent = true } catch { self.error = error.localizedDescription }; loading = false }
    func verify(_ env: AppEnvironment) async -> Bool { loading = true; error = nil; do { let response: EmailOTPVerifyResponse = try await env.session.perform("/api/v1/auth/email/verify", method: .post, body: EmailOTPVerifyRequest(email: email.trimmingCharacters(in: .whitespacesAndNewlines), code: code.trimmingCharacters(in: .whitespacesAndNewlines))); _ = try await env.session.installVerifiedSession(response); await env.bootstrap(); loading = false; return response.verified } catch { self.error = error.localizedDescription; loading = false; return false } }
}
struct AccountConnectionView: View {
    @EnvironmentObject private var env: AppEnvironment; @Environment(\.dismiss) private var dismiss; @StateObject private var model = AccountConnectionModel()
    var body: some View { ZStack { PingLetCanvas(); ScrollView { VStack(alignment: .leading, spacing: 22) { Image(systemName: "person.crop.circle.badge.checkmark").font(.system(size: 34)).foregroundStyle(Color.pingletClay); Text("Connect your email").font(.system(size: 40, design: .serif)); Text("Use the same email on another phone to return to everything you kept.").font(.system(size: 17, weight: .medium, design: .rounded)).foregroundStyle(Color.pingletMutedInk); PingLetCard { TextField("Email address", text: $model.email).textInputAutocapitalization(.never).keyboardType(.emailAddress).textContentType(.emailAddress); if model.sent { Divider(); TextField("Six-digit code", text: $model.code).keyboardType(.numberPad).textContentType(.oneTimeCode) } }; if let error = model.error { Label(error, systemImage: "exclamationmark.circle.fill").foregroundStyle(.red) }; Button(model.loading ? "PLEASE WAIT…" : model.sent ? "VERIFY EMAIL" : "SEND CODE") { Task { if model.sent { if await model.verify(env) { dismiss() } } else { await model.request(env) } } }.buttonStyle(PingLetPrimaryButtonStyle()).disabled(model.loading || model.email.isEmpty || (model.sent && model.code.count != 6)); Label("No password to remember", systemImage: "lock.shield").font(.system(size: 13, weight: .semibold, design: .rounded)).foregroundStyle(Color.pingletMutedInk).frame(maxWidth: .infinity) }.padding(24) } }.navigationTitle("Account").navigationBarTitleDisplayMode(.inline) }
}

struct TrialOfferView: View {
    @EnvironmentObject private var env: AppEnvironment; @Environment(\.dismiss) private var dismiss; @State private var loading = false; @State private var error: String?
    var body: some View { ZStack { PingLetCanvas(); ScrollView { VStack(alignment: .leading, spacing: 20) { PingLetSectionLabel(title: "PingLet Plus", trailing: "7 days"); Text("Try the whole experience.").font(.system(size: 42, design: .serif)); Text("Enjoy everything in Plus free for 7 days.").font(.system(size: 18, weight: .medium, design: .rounded)).foregroundStyle(Color.pingletMutedInk); PingLetCard(dark: true) { ForEach(["Full summaries, transcripts, insights, and takeaways", "Premium widget themes, profiles, and scheduled modes", "More AI imports and unlimited personal saves", "Personalized rotation and manual show-another controls"], id: \.self) { Label($0, systemImage: "checkmark.circle.fill").font(.system(size: 15, weight: .medium, design: .rounded)).foregroundStyle(Color.pingletPaper) } }; PingLetCard { Label("No payment required", systemImage: "shield.fill").font(.headline); Text("No card. No automatic subscription. You return to Free when the trial ends.").foregroundStyle(Color.pingletMutedInk) }; if let error { Text(error).foregroundStyle(.red) }; Button(loading ? "ACTIVATING…" : "TRY PLUS FREE") { Task { await start() } }.buttonStyle(PingLetPrimaryButtonStyle()).disabled(loading || env.entitlement?.trialEligible != true); Button("CONTINUE WITH FREE") { dismiss() }.font(.system(size: 13, weight: .bold, design: .rounded)).frame(maxWidth: .infinity) }.padding(24) } }.navigationTitle("PingLet Plus").navigationBarTitleDisplayMode(.inline) }
    private func start() async { loading = true; do { let entitlement: Entitlement = try await env.session.perform("/api/v1/me/entitlements/trial", method: .post, body: EmptyBody()); env.entitlement = entitlement; env.shared.entitlement = entitlement; await env.track("TRIAL_STARTED", metadata: "SETTINGS"); dismiss() } catch { self.error = "Your free trial could not be started. Refresh and try again." }; loading = false }
}

struct PlusPlansView: View {
    @EnvironmentObject private var env: AppEnvironment
    var body: some View { ZStack { PingLetCanvas(); ScrollView { VStack(alignment: .leading, spacing: 20) { PingLetSectionLabel(title: "PingLet Plus", trailing: "More room to remember"); Text("Keep everything worth remembering.").font(.system(size: 42, design: .serif)); Text("Complete understanding for every post, and a Home Screen that feels distinctly yours.").font(.system(size: 17, weight: .medium, design: .rounded)).foregroundStyle(Color.pingletMutedInk); PingLetCard(dark: true) { ForEach(["Complete AI breakdowns", "Every useful insight and takeaway", "50 social imports every month", "Unlimited personal saves", "Independent premium widget profiles"], id: \.self) { Label($0, systemImage: "checkmark.seal.fill").font(.system(size: 15, weight: .semibold, design: .rounded)).foregroundStyle(Color.pingletPaper) } }; PingLetCard { HStack { VStack(alignment: .leading, spacing: 4) { Text("ANNUAL").font(.caption.bold()).tracking(1.2).foregroundStyle(Color.pingletClay); Text("$14.99 per year").font(.system(size: 25, design: .serif)) }; Spacer(); Text("BEST VALUE").font(.caption.bold()).padding(.horizontal, 10).padding(.vertical, 6).background(Color.pingletMint, in: Capsule()) } }; PingLetCard { Text("MONTHLY").font(.caption.bold()).tracking(1.2).foregroundStyle(Color.pingletClay); Text("$1.99 per month").font(.system(size: 25, design: .serif)) }; Text("Apple subscription products must be configured before purchasing is enabled.").font(.system(size: 12, weight: .medium, design: .rounded)).foregroundStyle(Color.pingletMutedInk).multilineTextAlignment(.center).frame(maxWidth: .infinity); HStack { Spacer(); Link("Terms", destination: URL(string: "https://pinglet.ai/terms")!); Text("·"); Link("Privacy", destination: URL(string: "https://pinglet.ai/privacy")!); Spacer() }.font(.caption.bold()) }.padding(24).padding(.bottom, 30) } }.navigationTitle("PingLet Plus").navigationBarTitleDisplayMode(.inline) }
}
