import SwiftUI

@MainActor final class AccountConnectionModel: ObservableObject {
    @Published var email = ""; @Published var code = ""; @Published var sent = false; @Published var loading = false; @Published var error: String?
    func request(_ env: AppEnvironment) async { loading = true; error = nil; do { let _: EmailOTPResponse = try await env.session.perform("/api/v1/auth/email/request", method: .post, body: EmailOTPRequest(email: email.trimmingCharacters(in: .whitespacesAndNewlines))); sent = true } catch { self.error = error.localizedDescription }; loading = false }
    func verify(_ env: AppEnvironment) async -> Bool { loading = true; error = nil; do { let response: EmailOTPVerifyResponse = try await env.session.perform("/api/v1/auth/email/verify", method: .post, body: EmailOTPVerifyRequest(email: email.trimmingCharacters(in: .whitespacesAndNewlines), code: code.trimmingCharacters(in: .whitespacesAndNewlines))); _ = try await env.session.installVerifiedSession(response); await env.bootstrap(); loading = false; return response.verified } catch { self.error = error.localizedDescription; loading = false; return false } }
}
struct AccountConnectionView: View {
    @EnvironmentObject private var env: AppEnvironment; @Environment(\.dismiss) private var dismiss; @StateObject private var model = AccountConnectionModel()
    var body: some View { Form { Section { Text("Connect your email").font(.largeTitle).fontDesign(.serif); Text("Use the same email on another phone to return to your PingLets.") }; TextField("Email", text: $model.email).textInputAutocapitalization(.never).keyboardType(.emailAddress); if model.sent { TextField("Six-digit code", text: $model.code).keyboardType(.numberPad) }; if let error = model.error { Text(error).foregroundStyle(.red) }; Button(model.loading ? "PLEASE WAIT..." : model.sent ? "VERIFY EMAIL" : "SEND CODE") { Task { if model.sent { if await model.verify(env) { dismiss() } } else { await model.request(env) } } }.disabled(model.loading || model.email.isEmpty || (model.sent && model.code.count != 6)) }.navigationTitle("Account") }
}

struct TrialOfferView: View {
    @EnvironmentObject private var env: AppEnvironment; @Environment(\.dismiss) private var dismiss; @State private var loading = false; @State private var error: String?
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: 20) { Text("PINGLET PLUS").font(.caption.bold()); Text("Try PingLet Plus").font(.largeTitle).fontDesign(.serif); Text("Enjoy everything in Plus free for 7 days.").font(.title2); PingLetCard { ForEach(["Full summaries, transcripts, insights, and takeaways", "Premium widget themes, profiles, and scheduled modes", "More AI imports and unlimited personal saves", "Personalized rotation and manual show-another controls"], id: \.self) { Label($0, systemImage: "checkmark.circle.fill") } }; Label("No payment required", systemImage: "shield.fill").font(.headline); Text("No card. No automatic subscription."); if let error { Text(error).foregroundStyle(.red) }; Button(loading ? "ACTIVATING..." : "TRY PLUS FREE") { Task { await start() } }.buttonStyle(.borderedProminent).disabled(loading || env.entitlement?.trialEligible != true); Button("CONTINUE WITH FREE") { dismiss() } }.padding(24) }.background(Color.pingletBackground).navigationTitle("PingLet Plus") }
    private func start() async { loading = true; do { let entitlement: Entitlement = try await env.session.perform("/api/v1/me/entitlements/trial", method: .post, body: EmptyBody()); env.entitlement = entitlement; env.shared.entitlement = entitlement; await env.track("TRIAL_STARTED", metadata: "SETTINGS"); dismiss() } catch { self.error = "Your free trial could not be started. Refresh and try again." }; loading = false }
}

struct PlusPlansView: View {
    @EnvironmentObject private var env: AppEnvironment
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: 18) { Text("PINGLET PLUS").font(.caption.bold()); Text("Keep everything worth remembering.").font(.largeTitle).fontDesign(.serif); PingLetCard(dark: true) { Text("Complete AI breakdowns"); Text("Every useful insight"); Text("50 social imports monthly"); Text("Unlimited personal saves"); Text("Premium widget profiles") }; Text("Annual · $14.99 per year").font(.title2); Text("Monthly · $1.99 per month").font(.title2); Text("Apple subscription products must be configured before purchasing is enabled.").foregroundStyle(.secondary); Link("Terms", destination: URL(string: "https://pinglet.ai/terms")!); Link("Privacy", destination: URL(string: "https://pinglet.ai/privacy")!) }.padding(24) }.background(Color.pingletBackground).navigationTitle("PingLet Plus") }
}
