import SwiftUI
import WidgetKit

struct SettingsView: View {
    @EnvironmentObject private var env: AppEnvironment; @State private var deleting = false; @State private var deletionCodeSent = false; @State private var code = ""; @State private var error: String?
    var body: some View { NavigationStack { PingLetPage(eyebrow: "Settings", title: "Your PingLet, your rhythm.", subtitle: "A quieter place for your account and experience.") {
        accountCard
        accountActions
        Text("EXPERIENCE").font(.caption.bold()); PingLetCard { Text("Every 30 minutes").font(.headline); Text("Approximate timing, optimized for battery").foregroundStyle(.secondary); Picker("Content balance", selection: Binding(get: { env.shared.contentMix }, set: { value in env.shared.contentMix = value; Task { await patchMix(value) } })) { Text("Mine").tag("MOSTLY_MINE"); Text("Balanced").tag("BALANCED"); Text("Discover").tag("MORE_DISCOVERY") }.pickerStyle(.segmented); Text("Personal saves are always prioritized.").font(.caption); NavigationLink("Widget appearance") { WidgetSettingsView() }; Divider(); NavigationLink("Processing queue") { ProcessingQueueView() } }
        Text("ABOUT").font(.caption.bold()); PingLetCard { Text("PingLet for iOS"); Text("Version \(Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "0.1.7")").foregroundStyle(.secondary); Divider(); Link("Privacy policy", destination: URL(string: "https://pinglet.ai/privacy")!); Divider(); Link("Terms of service", destination: URL(string: "https://pinglet.ai/terms")!) }
        Text("Rotation can shift slightly while iOS is conserving battery.").font(.caption).foregroundStyle(.secondary)
    }.task { await env.refreshEntitlement() }.alert("Delete account and data?", isPresented: $deleting) { TextField("Verification code", text: $code); Button(deletionCodeSent ? "DELETE PERMANENTLY" : "SEND VERIFICATION CODE", role: .destructive) { Task { await deleteAction() } }; Button("CANCEL", role: .cancel) {} } message: { Text(deletionCodeSent ? "Enter the six-digit code sent to \(env.entitlement?.email ?? "your email"). This cannot be undone." : "This permanently deletes your account, personal saves, imports, favorites, devices, and account history.") } } }
    private var accountCard: some View { PingLetCard { let e = env.entitlement; HStack { VStack(alignment: .leading) { Text(e?.trialStatus == "ACTIVE" ? "PingLet Plus trial" : e?.plan == "PLUS" ? "PingLet Plus" : e?.isAnonymous == false ? "Free account" : "Guest profile").font(.title2); Text(e?.email ?? "Not connected to an email").foregroundStyle(.secondary) }; Spacer(); Text(e?.isAnonymous == false ? "VERIFIED" : "LOCAL").font(.caption.bold()) }; if let e { Divider(); HStack { Text("SAVES\n\(e.saveLimit.map { "\(e.saveCount) of \($0)" } ?? "Unlimited")"); Spacer(); Text("AI IMPORTS\n\(e.socialImportsUsed) of \(e.socialImportLimit)") }; if e.trialStatus == "ACTIVE" { Text("\(e.trialDaysRemaining) days of Plus remaining. Your account returns to Free automatically; you will not be charged.") }; if e.isAnonymous { Text("CONNECT EMAIL").font(.headline) } else { Divider(); HStack { Button("SIGN OUT") { Task { do { try await env.signOut() } catch { self.error = "Sign-out could not reach PingLet. Check your connection and try again." } } }; Spacer(); Button("DELETE ACCOUNT", role: .destructive) { deleting = true } } } }; if let error { Text(error).foregroundStyle(.red) } } }
    @ViewBuilder private var accountActions: some View {
        if env.entitlement?.isAnonymous != false { NavigationLink("CONNECT EMAIL") { AccountConnectionView() }.buttonStyle(.borderedProminent) }
        else if env.entitlement?.trialStatus != "ACTIVE" && env.entitlement?.plan != "PLUS" && env.entitlement?.trialEligible == true { NavigationLink("TRY PINGLET PLUS - 7 DAYS FREE") { TrialOfferView() }.buttonStyle(.borderedProminent) }
        if env.entitlement?.paidPlansEnabled == true && env.entitlement?.plan != "PLUS" { NavigationLink("VIEW PAID PLANS") { PlusPlansView() }.buttonStyle(.bordered) }
    }
    private func patchMix(_ value: String) async { struct Body: Encodable { let personalSystemMix: String }; let _: PreferenceResponse? = try? await env.session.perform("/api/v1/me/preferences", method: .patch, body: Body(personalSystemMix: value)) }
    private func deleteAction() async { guard let email = env.entitlement?.email else { return }; do { if !deletionCodeSent { let _: EmailOTPResponse = try await env.session.perform("/api/v1/auth/email/request", method: .post, body: EmailOTPRequest(email: email)); deletionCodeSent = true; deleting = true } else { struct Body: Encodable { let email: String; let code: String }; let _: BoolResponse = try await env.session.perform("/api/v1/auth/account", method: .delete, body: Body(email: email, code: code)); try await env.session.resetToAnonymous(); await env.bootstrap() } } catch { self.error = error.localizedDescription } }
}

struct ProcessingQueueView: View {
    @EnvironmentObject private var env: AppEnvironment; @State private var items: [Ingestion] = []; @State private var ready = Set<String>()
    var body: some View { List { if items.isEmpty { Text("No shared posts are processing.").foregroundStyle(.secondary) }; ForEach(items) { item in VStack(alignment: .leading, spacing: 5) { Text(item.contentItem?.text ?? item.caption ?? "Shared post").lineLimit(2); Text(item.processingStage ?? item.status).font(.caption).foregroundStyle(.secondary); if let message = item.errorMessage { Text(message).foregroundStyle(.red) } } } }.navigationTitle("Processing queue").task { while !Task.isCancelled { if let rows: [Ingestion] = try? await env.session.perform("/api/v1/me/ingestions") { let newReady = rows.filter { $0.status == "READY" && !ready.contains($0.id) }; items = rows; if !newReady.isEmpty { ready.formUnion(newReady.map(\.id)); await env.syncFeed() } }; try? await Task.sleep(for: .seconds(3)) } } }
}

struct WidgetSettingsView: View {
    @EnvironmentObject private var env: AppEnvironment; @State private var key = "default"; @State private var profile = WidgetProfile()
    private var plus: Bool { env.entitlement?.plan == "PLUS" }
    var body: some View { Form { Section("CHOOSE WIDGET") { Picker("Profile", selection: $key) { Text("Default").tag("default"); Text("Widget 2").tag("profile2"); Text("Widget 3").tag("profile3") } }; if !plus { Section { Text("Make every widget your own").font(.headline); Text("Plus unlocks themes, independent content profiles, schedules, typography, spacing, and manual rotation.") } }; Section("FREE CONTROLS") { Picker("Text scale", selection: $profile.textScale) { ForEach(["SMALL","MEDIUM","LARGE"], id: \.self, content: Text.init) }; Picker("Translucency", selection: $profile.opacity) { Text("Light").tag(62); Text("Blend").tag(78); Text("Solid").tag(90) } }; Section("PLUS APPEARANCE") { Picker("Surface", selection: $profile.theme) { ForEach(["BLEND","INK","FOREST","CLAY"], id: \.self, content: Text.init) }.disabled(!plus); Picker("Typography", selection: $profile.typography) { ForEach(["EDITORIAL","CLEAN","COMPACT"], id: \.self, content: Text.init) }.disabled(!plus); Picker("Spacing", selection: $profile.spacing) { ForEach(["COMPACT","COMFORTABLE","AIRY"], id: \.self, content: Text.init) }.disabled(!plus) }; Section("PLUS CONTENT PROFILE") { Picker("Source", selection: $profile.contentMode) { ForEach(["MIXED","PERSONAL","COLLECTIONS"], id: \.self, content: Text.init) }.disabled(!plus); Picker("Schedule", selection: $profile.scheduleMode) { Text("Anytime").tag("ANYTIME"); Text("Morning + evening").tag("DAY_RHYTHM"); Text("Contextual").tag("CONTEXTUAL") }.disabled(!plus); Toggle("Show another", isOn: $profile.manualNext).disabled(!plus) } }.navigationTitle("Widgets").onAppear { profile = env.shared.widgetProfile(key: key) }.onChange(of: key) { _, value in profile = env.shared.widgetProfile(key: value) }.onChange(of: profile) { _, value in env.shared.setWidgetProfile(value, key: key); WidgetCenter.shared.reloadAllTimelines() } }
}
